-- App-specific tweaks
source("~/.local/share/desktop/default/hypr/apps/1password.lua")
source("~/.local/share/desktop/default/hypr/apps/bitwarden.lua")
source("~/.local/share/desktop/default/hypr/apps/browser.lua")
source("~/.local/share/desktop/default/hypr/apps/desktop-shell.lua")
source("~/.local/share/desktop/default/hypr/apps/hyprshot.lua")
source("~/.local/share/desktop/default/hypr/apps/jetbrains.lua")
source("~/.local/share/desktop/default/hypr/apps/localsend.lua")
source("~/.local/share/desktop/default/hypr/apps/pip.lua")
source("~/.local/share/desktop/default/hypr/apps/qemu.lua")
source("~/.local/share/desktop/default/hypr/apps/retroarch.lua")
source("~/.local/share/desktop/default/hypr/apps/steam.lua")
source("~/.local/share/desktop/default/hypr/apps/system.lua")
source("~/.local/share/desktop/default/hypr/apps/terminals.lua")
source("~/.local/share/desktop/default/hypr/apps/walker.lua")
