# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = suppressevent maximize, class:.*

# Opacity values used when transparency is toggled on (opaque by default)
windowrule = opaque, class:.*
windowrule = opacity 0.97 0.9, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# App-specific tweaks
source = ~/.local/share/desktop/default/hypr/apps.conf
