# If not running interactively, don't do anything (leave this at the top of this file)
# [[ $- != *i* ]] && return

# Auto-launch fish shell if in interactive bash
# if command -v fish &> /dev/null; then
#	if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} && ${SHLVL} == 1 ]]
#	then
#		shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
#		exec fish $LOGIN_OPTION
#	fi
#fi

# All the default Desktop aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/desktop/default/bash/rc

# Source from .bashrc.d files
if [ -d ~/.bashrc.d ]; then
  for rc in ~/.bashrc.d/*; do
    if [ -f "$rc" ]; then
      . "$rc"
    fi
  done
fi
unset rc
