#!/usr/bin/env bash

# source "$DESKTOP_INSTALL/packaging/ansible.sh"
source "$DESKTOP_INSTALL/packaging/base.sh"
source "$DESKTOP_INSTALL/packaging/brave-browser.sh"
source "$DESKTOP_INSTALL/packaging/cargo.sh"
source "$DESKTOP_INSTALL/packaging/clamav.sh"
source "$DESKTOP_INSTALL/packaging/claude.sh"
# source "$DESKTOP_INSTALL/packaging/copilot.sh"
source "$DESKTOP_INSTALL/packaging/fish.sh"
source "$DESKTOP_INSTALL/packaging/fonts.sh"
source "$DESKTOP_INSTALL/packaging/github-cli.sh"
source "$DESKTOP_INSTALL/packaging/icons.sh"
source "$DESKTOP_INSTALL/packaging/kubectl.sh"
source "$DESKTOP_INSTALL/packaging/kubectx.sh"
source "$DESKTOP_INSTALL/packaging/kubie.sh"
source "$DESKTOP_INSTALL/packaging/lazygit.sh"
source "$DESKTOP_INSTALL/packaging/lazyvim.sh"
source "$DESKTOP_INSTALL/packaging/mc.sh"
source "$DESKTOP_INSTALL/packaging/neomutt.sh"
source "$DESKTOP_INSTALL/packaging/nvim.sh"
source "$DESKTOP_INSTALL/packaging/oc.sh"
source "$DESKTOP_INSTALL/packaging/opencode.sh"
# source "$DESKTOP_INSTALL/packaging/pass.sh"
source "$DESKTOP_INSTALL/packaging/restic.sh"
source "$DESKTOP_INSTALL/packaging/snapper.sh"
source "$DESKTOP_INSTALL/packaging/spotify.sh"
source "$DESKTOP_INSTALL/packaging/terraform.sh"
source "$DESKTOP_INSTALL/packaging/tmuxinator.sh"
source "$DESKTOP_INSTALL/packaging/tuis.sh"
# source "$DESKTOP_INSTALL/packaging/vault.sh"
source "$DESKTOP_INSTALL/packaging/vscode.sh"
source "$DESKTOP_INSTALL/packaging/webapps.sh"
source "$DESKTOP_INSTALL/packaging/yubikey.sh"
