#!/usr/bin/env bash

# source "$DESKTOP_INSTALL/packaging/ansible.sh"
source "$DESKTOP_INSTALL/packaging/base.sh"
source "$DESKTOP_INSTALL/packaging/cargo.sh"
# source "$DESKTOP_INSTALL/packaging/copilot.sh"
source "$DESKTOP_INSTALL/packaging/fonts.sh"
source "$DESKTOP_INSTALL/packaging/gh.sh"
# source "$DESKTOP_INSTALL/packaging/glab.sh"
source "$DESKTOP_INSTALL/packaging/icons.sh"
# source "$DESKTOP_INSTALL/packaging/kubectl.sh"
# source "$DESKTOP_INSTALL/packaging/kubectx.sh"
source "$DESKTOP_INSTALL/packaging/lazyvim.sh"
# source "$DESKTOP_INSTALL/packaging/oc.sh"
source "$DESKTOP_INSTALL/packaging/pass.sh"
# source "$DESKTOP_INSTALL/packaging/terraform.sh"
# source "$DESKTOP_INSTALL/packaging/tmuxinator.sh"
source "$DESKTOP_INSTALL/packaging/tuis.sh"
# source "$DESKTOP_INSTALL/packaging/vault.sh"
